lcgcmt_installarea=without_installarea
CMTPATH=/minerva/app/users/oaltinok/cmtuser/Minerva_nightly:/minerva/app/users/nightly/SLF5/Tue/minerva/MINERVA/MINERVA_v10r6p13:/minerva/app/users/nightly/SLF5/Tue/lhcb/LHCB/LHCB_v33r0p1:/minerva/app/users/nightly/SLF5/Tue/minerva/EXTERNAL/EXTERNAL_v10r6p13:/minerva/app/users/nightly/SLF5/Tue/lhcb/GEANT4/GEANT4_v94r2p2:/minerva/app/users/nightly/SLF5/Tue/minerva/MDBASE/MDBASE_v10r6p13:/minerva/app/users/nightly/SLF5/Tue/lhcb/GAUDI/GAUDI_v22r4:/minerva/app/users/nightly/SLF5/Tue/lcg/external/LCGCMT/LCGCMT_61
CMT_tag=$(tag)
CMTROOT=/grid/fermiapp/minerva/software_releases/nightly/SLF5/bookkeeping-head/workdir/Tue/contrib/CMT/v1r20p20090520
CMT_root=/grid/fermiapp/minerva/software_releases/nightly/SLF5/bookkeeping-head/workdir/Tue/contrib/CMT/v1r20p20090520
CMTVERSION=v1r20p20090520
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/minerva/app/users/oaltinok/cmtuser/Minerva_nightly/InstallArea/${CMTCONFIG}/bin:/minerva/app/users/nightly/SLF5/Tue/minerva/MINERVA/MINERVA_v10r6p13/InstallArea/${CMTCONFIG}/bin:/minerva/app/users/nightly/SLF5/Tue/lhcb/LHCB/LHCB_v33r0p1/InstallArea/${CMTCONFIG}/bin:/minerva/app/users/nightly/SLF5/Tue/lhcb/GEANT4/GEANT4_v94r2p2/InstallArea/${CMTCONFIG}/bin:/minerva/app/users/nightly/SLF5/Tue/lhcb/GAUDI/GAUDI_v22r4/InstallArea/${CMTCONFIG}/bin:/grid/fermiapp/minerva/software_releases/nightly/SLF5/bookkeeping-head/workdir/Tue/contrib/CMT/v1r20p20090520/${CMTBIN}:/minerva/app/users/nightly/SLF5/Tue/lhcb/GAUDI/GAUDI_v22r4/InstallArea/x86_64-slc5-gcc43-opt/scripts:/minerva/app/users/nightly/SLF5/Tue/lcg/external/sqlite/3.6.22/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/COOL/COOL_2_8_10a/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/pytools/1.5_python2.6/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/POOL/POOL_2_9_15/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/CORAL/CORAL_2_3_16a/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/XercesC/3.1.1p1/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/ROOT/5.30.00/x86_64-slc5-gcc43-opt/root/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/gccxml/0.9.0_20100114/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/tcmalloc/1.7/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/Python/2.6.5/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/gcc/4.3.5/x86_64-slc5/bin:/minerva/app/users/nightly/SLF5/Tue/lcg/external/mysql/5.5.14/x86_64-slc5-gcc43-opt/bin:/minerva/app/users/nightly/SLF5/Tue/minerva/EXTERNAL/EXTERNAL_v10r6p13/GENIE/bin:/grid/fermiapp/products/common/db/../prd/jobsub_tools/v1_2p/Linux-2/bin:/grid/fermiapp/products/common/prd/cpn/v1_6/NULL/bin:/grid/fermiapp/products/common/db/../prd/ifdhc/v1_3_2/Linux64bit-2-6-2-5-python26/bin:/grid/fermiapp/products/common/db/../prd/sam_web_client/v1_6/NULL/bin:/grid/fermiapp/products/minerva/prd/dcap/v2_32_f0408/Linux-2-4/bin:/grid/fermiapp/products/minerva/prd/sam/v8_8_5/Linux-2/bin:/grid/fermiapp/products/minerva/prd/ups/v4_7_4a/Linux-2/bin:/grid/fermiapp/minerva/postgres_client/bin/:/grid/fermiapp/minerva/valgrind-3.5.0/bin:/usr/krb5/bin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/minerva/app/users/nightly/SLF5/Tue/minerva/MinervaScripts:/grid/fermiapp/products/common/db/../prd/jobsub_tools/v1_2p/Linux-2/bin/condor_wrappers:/minerva/app/users/nightly/SLF5/Tue/minerva/MINERVA/MINERVA_v10r6p13/Tools/MinervaUtils/python:/minerva/app/users/nightly/SLF5/Tue/minerva/MINERVA/MINERVA_v10r6p13/Sim/MNVDetectormc/x86_64-slc5-gcc43-opt:/minerva/app/users/nightly/SLF5/Tue/minerva/EXTERNAL/EXTERNAL_v10r6p13/MINEXTERNAL/scripts
CLASSPATH=/grid/fermiapp/minerva/software_releases/nightly/SLF5/bookkeeping-head/workdir/Tue/contrib/CMT/v1r20p20090520/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=c++
cppflags=-pipe -ansi -pedantic -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=${symlink}
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=./
doc=./
inc=./
mgr=./
application_suffix=.exe
library_prefix=lib
lock_command=lockfile 
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=/usr/bin/python ${CMTROOT}/mgr/cmt_svn_checkout.py 
MAKEFLAGS= --no-print-directory 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=cp 
uninstall_command=/bin/rm -f 
cmt_installarea_command=ln -fs 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl54-gcc435
tag=x86_64-slc5-gcc43-opt
package=cmt_standalone
PACKAGE_ROOT=$(CMT_STANDALONEROOT)
srcdir=.
bin=./
BIN=/afs/fnal.gov/files/home/room2/oaltinok/NTupleAnalysis/v4_8/Input/Playlists/
javabin=./
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(GEANT4_installarea_prefix)/$(CMTCONFIG)/lib $(GEANT4_installarea_prefix)/share/lib $(GEANT4_installarea_prefix)/share/bin $(LHCB_installarea_prefix)/$(CMTCONFIG)/lib $(LHCB_installarea_prefix)/share/lib $(LHCB_installarea_prefix)/share/bin $(MINERVA_installarea_prefix)/$(CMTCONFIG)/lib $(MINERVA_installarea_prefix)/share/lib $(MINERVA_installarea_prefix)/share/bin $(MINERVA_nightly_installarea_prefix)/$(CMTCONFIG)/lib $(MINERVA_nightly_installarea_prefix)/share/lib $(MINERVA_nightly_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(cmt_standalone_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
LD_LIBRARY_PATH=/minerva/app/users/oaltinok/cmtuser/Minerva_nightly/InstallArea/${CMTCONFIG}/lib:/minerva/app/users/nightly/SLF5/Tue/minerva/MINERVA/MINERVA_v10r6p13/InstallArea/${CMTCONFIG}/lib:/minerva/app/users/nightly/SLF5/Tue/lhcb/LHCB/LHCB_v33r0p1/InstallArea/${CMTCONFIG}/lib:/minerva/app/users/nightly/SLF5/Tue/lhcb/GEANT4/GEANT4_v94r2p2/InstallArea/${CMTCONFIG}/lib:/minerva/app/users/nightly/SLF5/Tue/lhcb/GAUDI/GAUDI_v22r4/InstallArea/${CMTCONFIG}/lib:/minerva/app/users/nightly/SLF5/Tue/minerva/EXTERNAL/EXTERNAL_v10r6p13/GENIE/x86_64-slc5-gcc43-opt:/grid/fermiapp/minerva/sharedlib/x86_64-slc5-gcc43-opt/:/minerva/app/users/nightly/SLF5/Tue/minerva/EXTERNAL/EXTERNAL_v10r6p13/LOG4CPP/x86_64-slc5-gcc43-opt:/minerva/app/users/nightly/SLF5/Tue/minerva/EXTERNAL/EXTERNAL_v10r6p13/GDML/x86_64-slc5-gcc43-opt:/minerva/app/users/nightly/SLF5/Tue/lcg/external/sqlite/3.6.22/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/COOL/COOL_2_8_10a/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/HepMC/2.06.05/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/pytools/1.5_python2.6/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/HepPDT/2.06.01/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/RELAX/RELAX_1_3_0/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/POOL/POOL_2_9_15/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/CORAL/CORAL_2_3_16a/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/clhep/1.9.4.7/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/GSL/1.10/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/XercesC/3.1.1p1/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/uuid/1.38p1/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/Boost/1.44.0_python2.6/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/ROOT/5.30.00/x86_64-slc5-gcc43-opt/root/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/tcmalloc/1.7/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/libunwind/5c2cade/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/lcg/external/gcc/4.3.5/x86_64-slc5/lib64:/minerva/app/users/nightly/SLF5/Tue/minerva/EXTERNAL/EXTERNAL_v10r6p13/MinosGeom/x86_64-slc5-gcc43-opt:/minerva/app/users/nightly/SLF5/Tue/minerva/EXTERNAL/EXTERNAL_v10r6p13/NumiBeamDB/x86_64-slc5-gcc43-opt:/minerva/app/users/nightly/SLF5/Tue/lcg/external/mysql/5.5.14/x86_64-slc5-gcc43-opt/lib:/minerva/app/users/nightly/SLF5/Tue/minerva/EXTERNAL/EXTERNAL_v10r6p13/PYTHIA6/lib:/grid/fermiapp/products/common/db/../prd/ifdhc/v1_3_2/Linux64bit-2-6-2-5-python26/lib:/grid/fermiapp/products/minerva/prd/dcap/v2_32_f0408/Linux-2-4/lib:/grid/fermiapp/minerva/postgres_client/lib/:/usr/lib64:/usr/lib:/minerva/app/users/nightly/SLF5/Tue/minerva/MINERVA/MINERVA_v10r6p13/Ana/UnfoldUtils/x86_64-slc5-gcc43-opt:/minerva/app/users/nightly/SLF5/Tue/lcg/external/Python/2.6.5/x86_64-slc5-gcc43-opt/lib
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
MDBASE_installarea_prefix=$(cmt_installarea_prefix)
MDBASE_installarea_prefix_remove=$(MDBASE_installarea_prefix)
GEANT4_installarea_prefix=$(cmt_installarea_prefix)
GEANT4_installarea_prefix_remove=$(GEANT4_installarea_prefix)
EXTERNAL_installarea_prefix=$(cmt_installarea_prefix)
EXTERNAL_installarea_prefix_remove=$(EXTERNAL_installarea_prefix)
LHCB_installarea_prefix=$(cmt_installarea_prefix)
LHCB_installarea_prefix_remove=$(LHCB_installarea_prefix)
MINERVA_installarea_prefix=$(cmt_installarea_prefix)
MINERVA_installarea_prefix_remove=$(MINERVA_installarea_prefix)
MINERVA_nightly_installarea_prefix=$(cmt_installarea_prefix)
MINERVA_nightly_installarea_prefix_remove=$(MINERVA_nightly_installarea_prefix)
cmt_installarea_linkopts= -L/minerva/app/users/oaltinok/cmtuser/Minerva_nightly/$(MINERVA_nightly_installarea_prefix)/$(CMTCONFIG)/lib  -L/minerva/app/users/nightly/SLF5/Tue/minerva/MINERVA/MINERVA_v10r6p13/$(MINERVA_installarea_prefix)/$(CMTCONFIG)/lib  -L/minerva/app/users/nightly/SLF5/Tue/lhcb/LHCB/LHCB_v33r0p1/$(LHCB_installarea_prefix)/$(CMTCONFIG)/lib  -L/minerva/app/users/nightly/SLF5/Tue/lhcb/GEANT4/GEANT4_v94r2p2/$(GEANT4_installarea_prefix)/$(CMTCONFIG)/lib  -L/minerva/app/users/nightly/SLF5/Tue/lhcb/GAUDI/GAUDI_v22r4/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib 
use_requirements=requirements $(CMT_root)/mgr/requirements 
use_includes= 
use_fincludes= $(use_includes)
use_stamps=  $(cmt_standalone_stamps) 
use_cflags=  $(cmt_standalone_cflags) 
use_pp_cflags=  $(cmt_standalone_pp_cflags) 
use_cppflags=  $(cmt_standalone_cppflags) 
use_pp_cppflags=  $(cmt_standalone_pp_cppflags) 
use_fflags=  $(cmt_standalone_fflags) 
use_pp_fflags=  $(cmt_standalone_pp_fflags) 
includes= $(ppcmd)"$(srcdir)" $(use_includes)
fincludes= $(includes)
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
all_constituents= $(constituents)
constituentsclean= 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
